# Generated by Django 4.0.4 on 2022-05-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creationDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='destructionDate',
            field=models.DateTimeField(),
        ),
    ]
